# Generated by Django 5.1.4 on 2025-01-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Enter the firmware version', max_length=50, unique=True)),
                ('release_date', models.DateField(help_text='Enter the release date of the firmware')),
                ('description', models.TextField(help_text='Enter the description of the firmware')),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmwares',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter the username', max_length=100)),
                ('password', models.CharField(help_text='Enter the password', max_length=255)),
                ('email', models.EmailField(help_text='Enter the email address', max_length=100, unique=True)),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Enter the device name', max_length=100)),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator')], help_text='Select the device type', max_length=8)),
                ('device_status', models.BooleanField(default=False, help_text='Indicate the device status')),
                ('device_location', models.CharField(help_text='Enter the device location', max_length=100)),
                ('device_last_updated', models.DateTimeField(auto_now=True)),
                ('firmware', models.ForeignKey(help_text='Select the firmware version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.firmware')),
                ('device_owner', models.ForeignKey(help_text='Select the device owner', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.user')),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='GPIOPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.PositiveIntegerField(help_text='Enter the GPIO pin number', unique=True)),
                ('is_led', models.BooleanField(default=False, help_text='Indicates if the pin is connected to an LED')),
                ('device', models.ForeignKey(help_text='Select the associated device', on_delete=django.db.models.deletion.CASCADE, related_name='gpio_pins', to='api.iotdevice')),
            ],
            options={
                'verbose_name': 'GPIO Pin',
                'verbose_name_plural': 'GPIO Pins',
                'ordering': ['pin_number'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.TextField(help_text='Enter the log entry')),
                ('device', models.ForeignKey(help_text='Select the associated device', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.iotdevice')),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_status', models.BooleanField(default=False, help_text='The current state of the button (pressed or not)')),
                ('gpio_pin', models.OneToOneField(help_text='Select the GPIO pin for this button', on_delete=django.db.models.deletion.CASCADE, related_name='button', to='api.gpiopin')),
                ('device', models.ForeignKey(help_text='Select the associated IoT device', on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='api.iotdevice')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
            },
        ),
        migrations.CreateModel(
            name='ActuatorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(help_text='Enter the actuator command', max_length=100)),
                ('device', models.ForeignKey(help_text='Select the associated device', on_delete=django.db.models.deletion.CASCADE, related_name='actuator_commands', to='api.iotdevice')),
            ],
            options={
                'verbose_name': 'Actuator Command',
                'verbose_name_plural': 'Actuator Commands',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_status', models.BooleanField(default=False, help_text='The current state of the LED (on or off)')),
                ('device', models.ForeignKey(help_text='Select the associated IoT device', on_delete=django.db.models.deletion.CASCADE, related_name='leds', to='api.iotdevice')),
                ('gpio_pin', models.OneToOneField(help_text='Select the GPIO pin for this LED', on_delete=django.db.models.deletion.CASCADE, related_name='led', to='api.gpiopin')),
            ],
            options={
                'verbose_name': 'LED',
                'verbose_name_plural': 'LEDs',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(help_text='Enter the sensor data in JSON format')),
                ('device', models.ForeignKey(help_text='Select the associated device', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='api.iotdevice')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Enter the notification message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, help_text='Indicate if the notification has been read')),
                ('user', models.ForeignKey(help_text='Select the user to notify', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
