# Generated by Django 5.1.4 on 2025-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='device_id',
        ),
    ]
