# Generated by Django 5.1.4 on 2025-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_led_button_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='led',
            old_name='gpio',
            new_name='led_pin',
        ),
    ]
