# Generated by Django 5.1.4 on 2025-01-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_led'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
